import React, { useMemo, useState } from "react";
import { Sprout, Search, MapPin, Bell, Menu, ChevronDown, SlidersHorizontal, Star, Heart, ArrowUpRight, Tractor, CalendarDays, ShieldCheck, Wallet, Leaf, MessageCircle, X, Check, Plus, Clock3, Sparkles, LayoutDashboard, Package, CircleHelp, IndianRupee, Users, TrendingUp, ChevronRight } from "lucide-react";

const equipment = [
 {id:1,name:"Mahindra 575 DI Tractor",category:"Tractors",price:1600,unit:"day",location:"Anandapuram · 4.2 km",rating:4.9,reviews:28,owner:"Ramesh Kumar",image:"https://images.unsplash.com/photo-1592982537447-6f2a6a0f5c2b?auto=format&fit=crop&w=900&q=85",tag:"Popular",power:"45 HP",desc:"Reliable 45 HP tractor for ploughing, cultivation and hauling."},
 {id:2,name:"Combine Harvester",category:"Harvesters",price:6500,unit:"day",location:"Pendurthi · 8.5 km",rating:4.8,reviews:16,owner:"Sri Lakshmi Farms",image:"https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=85",tag:"High demand",power:"Multi-crop",desc:"Efficient harvesting for paddy and other seasonal crops."},
 {id:3,name:"Power Sprayer 20L",category:"Sprayers",price:350,unit:"day",location:"Kothavalasa · 2.1 km",rating:4.7,reviews:41,owner:"Srinivas Naidu",image:"https://images.unsplash.com/photo-1523742818810-4f7b7b2b9c9c?auto=format&fit=crop&w=900&q=85",tag:"Budget pick",power:"20 litre",desc:"Lightweight sprayer for crop care and pest management."},
 {id:4,name:"Rotavator 6 Feet",category:"Tillers",price:900,unit:"day",location:"Anandapuram · 5.8 km",rating:4.8,reviews:19,owner:"Vijaya Equipment Hub",image:"https://images.unsplash.com/photo-1594771804886-a933bb2d609b?auto=format&fit=crop&w=900&q=85",tag:"Available today",power:"6 ft",desc:"Prepare seedbeds and break up soil after ploughing."},
 {id:5,name:"Seed Drill Machine",category:"Seeders",price:750,unit:"day",location:"Bheemunipatnam · 9.2 km",rating:4.6,reviews:12,owner:"Kiran Agriculture",image:"https://images.unsplash.com/photo-1499529112087-3cb3b73cee0d?auto=format&fit=crop&w=900&q=85",tag:"New listing",power:"9 rows",desc:"Consistent seed placement to make sowing easier."},
 {id:6,name:"Mini Tiller",category:"Tillers",price:550,unit:"day",location:"Sabbavaram · 6.4 km",rating:4.7,reviews:22,owner:"Ramesh Kumar",image:"https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=85",tag:"Easy to use",power:"7 HP",desc:"Compact tiller for vegetable plots and smaller fields."}
];
const categories=[["All equipment","⌘"],["Tractors","🚜"],["Harvesters","🌾"],["Sprayers","💧"],["Tillers","⚙️"],["Seeders","🌱"]];
function App(){
 const [role,setRole]=useState("Farmer"); const [active,setActive]=useState("Discover"); const [category,setCategory]=useState("All equipment"); const [query,setQuery]=useState(""); const [maxPrice,setMaxPrice]=useState(7000); const [filterOpen,setFilterOpen]=useState(false); const [selected,setSelected]=useState(null); const [booked,setBooked]=useState([]); const [notice,setNotice]=useState(""); const [aiOpen,setAiOpen]=useState(false); const [aiText,setAiText]=useState(""); const [aiAnswer,setAiAnswer]=useState(""); const [favorites,setFavorites]=useState([]);
 const filtered=useMemo(()=>equipment.filter(e=>(category==="All equipment"||e.category===category)&&(e.name+" "+e.category+" "+e.location).toLowerCase().includes(query.toLowerCase())&&e.price<=maxPrice),[category,query,maxPrice]);
 const flash=(s)=>{setNotice(s);setTimeout(()=>setNotice(""),2800)};
 const book=(item)=>{setBooked(old=>old.includes(item.id)?old:[...old,item.id]);setSelected(null);flash("Booking request sent to "+item.owner+"!");};
 return <div className="app-shell">
  <aside className="sidebar">
   <div className="brand"><div className="brand-mark"><Sprout size={23}/></div><div><b>AgriRent</b><span>GROW TOGETHER</span></div></div>
   <div className="workspace"><span className="tiny-label">WORKSPACE</span><button className={"nav-link "+(active==="Discover"?"selected":"")} onClick={()=>setActive("Discover")}><Search size={18}/> Discover equipment</button><button className={"nav-link "+(active==="Bookings"?"selected":"")} onClick={()=>setActive("Bookings")}><CalendarDays size={18}/> My bookings <span className="nav-count">{booked.length||"2"}</span></button><button className={"nav-link "+(active==="Saved"?"selected":"")} onClick={()=>setActive("Saved")}><Heart size={18}/> Saved equipment</button><button className={"nav-link "+(active==="Messages"?"selected":"")} onClick={()=>setActive("Messages")}><MessageCircle size={18}/> Messages <span className="unread-dot"/></button>
   <div className="side-divider"/><span className="tiny-label">YOUR FARM</span><button className={"nav-link "+(active==="Insights"?"selected":"")} onClick={()=>setActive("Insights")}><TrendingUp size={18}/> Farm insights</button><button className={"nav-link "+(active==="Help"?"selected":"")} onClick={()=>setActive("Help")}><CircleHelp size={18}/> Help & support</button>
   </div>
   <div className="side-bottom"><div className="weather-card"><div className="weather-top"><span>LOCAL WEATHER</span><span>☀️ 29°</span></div><b>Good day for field work</b><p>Clear skies expected today in Anandapuram.</p><div className="weather-foot"><span>Humidity 62%</span><span>Rain 10%</span></div></div><div className="profile-row"><div className="avatar">RK</div><div className="profile-info"><b>Ravi Kumar</b><span>Farmer account</span></div><ChevronDown size={16} color="#728176"/></div></div>
  </aside>
  <main className="main-area">
   <header className="topbar"><div className="crumb"><span>Workspace</span><ChevronRight size={14}/><b>{active}</b></div><div className="top-actions"><button className="role-switch" onClick={()=>{setRole(role==="Farmer"?"Owner":"Farmer");flash("Switched to "+(role==="Farmer"?"Owner":"Farmer")+" demo view")}}><span className="role-dot"/>{role} view<ChevronDown size={14}/></button><button className="icon-button" aria-label="Notifications" onClick={()=>flash("You're all caught up")}><Bell size={18}/><i/></button><div className="top-avatar">RK</div></div></header>
   <div className="content">
    {active==="Discover" ? <>
     <section className="welcome-row"><div><div className="eyebrow"><span className="eyebrow-line"/> YOUR FARMING, SIMPLIFIED</div><h1>Good morning, Ravi <span className="wave">✳</span></h1><p className="subtitle">The right equipment, right when you need it.</p></div><button className="list-equipment" onClick={()=>{setRole("Owner");setActive("Owner dashboard")}}><Plus size={17}/> List your equipment</button></section>
     <section className="hero-banner"><div className="hero-copy"><div className="hero-pill"><Sparkles size={13}/> SMART FARMING, MADE SIMPLE</div><h2>Big harvests start<br/>with the <em>right tools.</em></h2><p>Rent trusted farm equipment from people<br/>in your community. No big investments.</p><button className="hero-button" onClick={()=>document.getElementById("equipment-grid")?.scrollIntoView({behavior:"smooth"})}>Explore equipment <ArrowUpRight size={16}/></button><div className="hero-trust"><span><ShieldCheck size={14}/> Verified owners</span><span><Wallet size={14}/> Fair local prices</span></div></div><div className="hero-art"><div className="sun-disc"/><div className="field field-one"/><div className="field field-two"/><div className="field field-three"/><div className="tractor-emoji">🚜</div><div className="hero-stat"><span className="stat-icon"><Users size={16}/></span><div><b>1,200+</b><small>local farmers</small></div><span className="stat-up">↗</span></div></div></section>
     <section className="quick-stats"><div className="quick-stat"><div className="stat-symbol green"><Tractor size={19}/></div><div><span>Equipment nearby</span><b>248 <small>available</small></b></div><div className="stat-trend">+12%</div></div><div className="quick-stat"><div className="stat-symbol orange"><CalendarDays size={19}/></div><div><span>Your bookings</span><b>{booked.length+2} <small>this season</small></b></div><div className="stat-trend neutral">View all ↗</div></div><div className="quick-stat"><div className="stat-symbol blue"><IndianRupee size={19}/></div><div><span>Potential savings</span><b>₹18,400 <small>this year</small></b></div><div className="stat-trend">+18%</div></div></section>
     <section className="equipment-section" id="equipment-grid"><div className="section-heading"><div><h2>Find your equipment</h2><p>Reliable tools from trusted farmers around you.</p></div><button className="text-link" onClick={()=>{setCategory("All equipment");setQuery("");setMaxPrice(7000)}}>View all equipment <ArrowUpRight size={15}/></button></div>
      <div className="search-toolbar"><div className="searchbox"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tractors, harvesters, sprayers..."/><kbd>⌘ K</kbd></div><button className={"filter-button "+(filterOpen?"filter-active":"")} onClick={()=>setFilterOpen(!filterOpen)}><SlidersHorizontal size={17}/> Filters <span className="filter-badge">1</span></button><div className="sort-label">Sort by <select aria-label="Sort equipment" onChange={()=>{}}><option>Recommended</option><option>Price: low to high</option><option>Top rated</option></select></div></div>
      {filterOpen&&<div className="filter-panel"><label>Maximum daily price <b>₹{maxPrice.toLocaleString("en-IN")}</b><input type="range" min="300" max="7000" step="100" value={maxPrice} onChange={e=>setMaxPrice(Number(e.target.value))}/></label><button onClick={()=>{setMaxPrice(7000);setCategory("All equipment")}}>Reset filters</button></div>}
      <div className="category-row">{categories.map(([name,emoji])=><button key={name} className={"category-chip "+(category===name?"active":"")} onClick={()=>setCategory(name)}><span>{emoji}</span>{name}</button>)}</div>
      <div className="equipment-grid">{filtered.map(item=><article className="equipment-card" key={item.id}><div className="equipment-image" style={{backgroundImage:`linear-gradient(180deg,rgba(16,31,22,.02),rgba(16,31,22,.08)),url("${item.image}")`}}><span className="image-tag">{item.tag}</span><button className={"favorite "+(favorites.includes(item.id)?"favorited":"")} aria-label="Save equipment" onClick={()=>setFavorites(old=>old.includes(item.id)?old.filter(x=>x!==item.id):[...old,item.id])}><Heart size={17} fill={favorites.includes(item.id)?"currentColor":"none"}/></button></div><div className="equipment-info"><div className="equipment-title"><h3>{item.name}</h3><span className="rating"><Star size={13} fill="currentColor"/>{item.rating}</span></div><div className="equipment-location"><MapPin size={13}/>{item.location}</div><div className="equipment-meta"><span><Tractor size={13}/>{item.power}</span><span><ShieldCheck size={13}/> Verified owner</span></div><div className="equipment-card-foot"><div className="price"><b>₹{item.price.toLocaleString("en-IN")}</b><span>/ {item.unit}</span></div><button className="book-button" onClick={()=>setSelected(item)}>Book now <ArrowUpRight size={14}/></button></div></div></article>)}</div>
      {filtered.length===0&&<div className="empty-state"><Search size={25}/><b>No equipment found</b><p>Try another keyword or adjust your filters.</p><button onClick={()=>{setQuery("");setCategory("All equipment");setMaxPrice(7000)}}>Clear filters</button></div>}
      <div className="nearby-note"><div className="nearby-icon"><MapPin size={19}/></div><div><b>Looking for something closer?</b><p>Explore equipment available in nearby villages and mandals.</p></div><button onClick={()=>flash("Map view is coming soon in this demo.")}>Explore map <ArrowUpRight size={15}/></button></div>
     </section>
    </> : active==="Bookings" ? <section className="alt-page"><div className="eyebrow">YOUR ACTIVITY</div><h1>My bookings</h1><p className="subtitle">Keep track of your equipment rentals.</p>{[...booked.map(id=>equipment.find(e=>e.id===id)).filter(Boolean),equipment[0],equipment[2]].map((e,i)=><div className="booking-row" key={i}><div className="booking-thumb" style={{backgroundImage:`url("${e.image}")`}}/><div className="booking-main"><b>{e.name}</b><span><CalendarDays size={13}/> {i===0&&booked.length?"Requested just now":"12 Oct – 13 Oct, 2026"}</span></div><span className={"status "+(i===0&&booked.length?"pending":"confirmed")}>{i===0&&booked.length?"Pending":"Confirmed"}</span><b className="booking-price">₹{e.price.toLocaleString("en-IN")}/day</b></div>)}</section> : active==="Saved" ? <section className="alt-page"><div className="eyebrow">YOUR SHORTLIST</div><h1>Saved equipment</h1><p className="subtitle">Equipment you want to come back to.</p><div className="saved-grid">{equipment.filter(e=>favorites.includes(e.id)).map(e=><button className="saved-item" key={e.id} onClick={()=>setSelected(e)}><img src={e.image}/><b>{e.name}</b><span>₹{e.price.toLocaleString("en-IN")} / day</span></button>)}</div>{!favorites.length&&<div className="empty-state"><Heart size={24}/><b>No saved equipment yet</b><p>Tap the heart on any equipment card to save it here.</p><button onClick={()=>setActive("Discover")}>Browse equipment</button></div>}</section> : <section className="alt-page"><div className="eyebrow">AGRI RENT WORKSPACE</div><h1>{active==="Owner dashboard"?"Owner dashboard":active}</h1><p className="subtitle">{active==="Owner dashboard"?"Manage your listings, booking requests, and earnings.":"Tools and updates to help your farm thrive."}</p><div className="owner-metrics"><div><span>Total earnings</span><b>₹24,650</b><small>↑ 12.8% this month</small></div><div><span>Active listings</span><b>08</b><small>6 available now</small></div><div><span>Booking requests</span><b>03</b><small>Needs your response</small></div></div><div className="owner-panel"><h3>Recent booking requests</h3>{equipment.slice(0,3).map((e,i)=><div className="booking-row" key={e.id}><div className="booking-thumb" style={{backgroundImage:`url("${e.image}")`}}/><div className="booking-main"><b>{e.name}</b><span>{["Ravi Kumar","Suresh Naidu","Lakshmi Devi"][i]} · {["Tomorrow","12 Oct","14 Oct"][i]}</span></div><span className="status pending">Needs review</span><button className="approve" onClick={()=>flash("Booking request approved in demo.")}><Check size={14}/> Approve</button></div>)}</div></section>}
    <footer className="footer"><span>© 2026 AgriRent</span><span>Built for farmers, powered by community <Leaf size={13}/></span><span>English <ChevronDown size={13}/></span></footer>
   </div>
  </main>
  <button className="ai-fab" onClick={()=>setAiOpen(true)}><Sparkles size={18}/><span>Ask AgriMate</span></button>
  {aiOpen&&<div className="drawer-backdrop" onClick={()=>setAiOpen(false)}><aside className="ai-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div className="ai-brand"><div><Sparkles size={19}/></div><span><b>AgriMate</b><small>Your farming companion</small></span></div><button className="icon-button" onClick={()=>setAiOpen(false)}><X size={19}/></button></div><div className="ai-intro"><div className="ai-big-icon">🌱</div><h2>How can I help your farm?</h2><p>Ask about equipment, crop planning, or how to save on rentals.</p></div><div className="suggestions"><button onClick={()=>{setAiText("Which equipment is best for preparing my field?");setAiAnswer("For field preparation, a tractor with a rotavator is a good starting point. For smaller plots, a mini tiller may cost less. Check the soil condition and acreage before choosing.")}}>🌾 Best equipment for my field</button><button onClick={()=>{setAiText("How can I reduce rental costs?");setAiAnswer("Book only for the time you need, compare nearby owners, and coordinate with neighbouring farmers to share transport costs. Early booking during peak season can also help.")}}>💰 Tips to reduce rental costs</button><button onClick={()=>{setAiText("What should I check before renting?");setAiAnswer("Confirm availability, inspect the machine, agree on fuel and transport charges, ask about operator support, and record the return condition before starting.")}}>🛠️ Before I rent a machine</button></div>{aiAnswer&&<div className="ai-response"><span><Sparkles size={13}/> AGRIMATE</span>{aiAnswer}</div>}<form className="ai-input" onSubmit={e=>{e.preventDefault();setAiAnswer("I can help with equipment selection, rental planning, and general farm tips. For specific crop or disease advice, share your crop and local conditions.");setAiText("")}}><input value={aiText} onChange={e=>setAiText(e.target.value)} placeholder="Ask anything about your farm..."/><button aria-label="Send message"><ArrowUpRight size={18}/></button></form><p className="ai-disclaimer">Demo assistant · Answers are illustrative, not live AI advice.</p></aside></div>}
  {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="booking-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}><X size={18}/></button><div className="modal-photo" style={{backgroundImage:`url("${selected.image}")`}}/><div className="modal-body"><span className="modal-kicker">EQUIPMENT DETAILS</span><h2>{selected.name}</h2><div className="modal-location"><MapPin size={14}/>{selected.location} <span>·</span><Star size={13} fill="currentColor"/>{selected.rating} ({selected.reviews} reviews)</div><p>{selected.desc}</p><div className="owner-chip"><div className="avatar">✓</div><div><b>{selected.owner}</b><span>Verified equipment owner</span></div><ShieldCheck size={18} color="#21845d"/></div><div className="booking-dates"><label>Start date<input type="date" defaultValue="2026-10-12"/></label><label>End date<input type="date" defaultValue="2026-10-13"/></label></div><div className="modal-total"><span>Estimated total <small>· 1 day</small></span><b>₹{selected.price.toLocaleString("en-IN")}</b></div><button className="confirm-book" onClick={()=>book(selected)}>Request booking <ArrowUpRight size={17}/></button><small className="modal-note"><ShieldCheck size={13}/> No payment taken in this demo.</small></div></div></div>}
  {notice&&<div className="toast"><Check size={17}/>{notice}</div>}
 </div>
}
export default App;
